# Site settings ...
uri: https://mortuzahossain.github.io/assembly/
url: https://mortuzahossain.github.io/assembly/
name: Md Mortuza Hossain
title: 8086 Assignment
email: mortuzahossain1997@gmail.com
author: mortuzahossain
keywords: "Assignment,asm,project"
description: "This website contain the solve of first assignment of 8086 microprocessors ğŸ’€ğŸ’€assignmentğŸ’€ğŸ’€ solveğŸ¤“ğŸ¤“. Use this for practiceğŸ‘¨â€ğŸ³ğŸ‘¨â€ğŸ³ğŸ‘¨â€ğŸ³ not to cheatğŸ™ğŸ™ğŸ™ğŸ™ğŸ™. Try to understand the codeğŸ‘©â€ğŸ’» ğŸ‘¨â€ğŸ’» and shareğŸ‘¨â€ğŸ‘¨â€ğŸ‘¦â€ğŸ‘¦ ğŸ‘¨â€ğŸ‘¨â€ğŸ‘§â€ğŸ‘§ ğŸ‘©â€ğŸ‘¦ ğŸ‘©â€ğŸ‘§ ğŸ‘©â€ğŸ‘§â€ğŸ‘¦ ğŸ‘©â€ğŸ‘¦â€ğŸ‘¦ ğŸ‘©â€ğŸ‘§â€ğŸ‘§ ğŸ‘¨â€ğŸ‘¦ ğŸ‘¨ if it help you. Wish you good luck. ğŸ˜€ ğŸ˜ƒ ğŸ˜"
social_username: mortuzahossain

# Build settings ...
sass:
  style: compressed
markdown: kramdown
paginate: 20
permalink: /post/:title
paginate_path: "assembly/page/:num/"
exclude:
  - README.md

# Plugins ...
plugins:
  - jekyll-paginate
  - jemoji